export { default as Navbar } from './Navbar'
export { default as Footer } from './Footer'
export { default as CallToAction } from './CallToAction'
export { default as FirstVersion } from './FirstVersion'
export { default as WhoWeAre } from './WhoWeAre'
export { default as Team } from './Team'
